### ISSUE TITLE
[Feature] It awesome :)

### ISSUE THREAD

**Issue by Rogal80** [Kahsolt/stable-diffusion-webui-hires-fix-progressive#1]
Hi, script is outstanding, but can it be like some other extension already placed in UI rather than under scripts, for example like in those in green frame?  
This will unblock other scripts to use together
![image](https://user-images.githubusercontent.com/112553453/213933865-c1cc58ad-34d1-42c3-8e55-bd2d21b067f3.png)

**Comment by Kahsolt** [comment]
Got it!

**Comment by Rogal80** [comment]
Thank you :)

**Comment by Rogal80** [comment]
Ok, now it is in dropdown list, but it seems that stopped working :(

Windows,Firefox
Commit hash: c98cb0f8ecc904666f47684e238dd022039ca16f
--xformers --api --listen --enable-insecure-extension-access

**Comment by Rogal80** [comment]
I think it should have a switch like in the save intermediate extension to turn on and off

![image](https://user-images.githubusercontent.com/112553453/213981630-fd98c5d1-b714-487a-bc5c-1d70bd679fe7.png)

**Comment by Cyberforensix** [comment]
Yes stopped working because now it does not get invoked, it needs a trigger for that. Have a look at this extension and how they have it solved:

https://github.com/fkthebez/Animetard

**Comment by Kahsolt** [comment]
Hi friends :) Just came back from holiday to see what's wrong, now I understand...

For a `AlwaysVisible` extension, webui only gives us four hooks: `process()`, `process_batch()`,  `postprocess_batch()` and `postprocess()`, which **surrounds** the core code of `process_images_inner()`.
However, this progressive hires.fix needs to take control of that part in order to make the procedure iterative. This requires the `run()` hook which only works for extension in the dropdown list. 🤔

So currently it cannot be `AlwaysVisible`, I have to just roll everything back :)

**Comment by Rogal80** [comment]
Hi, any chance in the future to have it in the dropdown?

**Comment by Kahsolt** [comment]
🤔 seems not possible, unless this mechanism is implemented in the webui core, rather then a wrapper script.
(This might also be why the original hires.fix is still coupled in the core and could not be separated out as a pluggable

**Comment by Kahsolt** [comment]
Have forgot this thread so long...
Now it can work in two morphs, switching by a local config,
So might have solved the issue 🤔, now temporarily close it.
